// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// gfytuuuuu
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg-oKE9BplgVT90lAp1aslt3VZPAoUfxw',
    appId: '1:723344246922:web:4bd1a81261d106c8540573',
    messagingSenderId: '723344246922',
    projectId: 'roommate-c6d62',
    authDomain: 'roommate-c6d62.firebaseapp.com',
    storageBucket: 'roommate-c6d62.firebasestorage.app',
    measurementId: 'G-VSNGJ0VDQR',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALC3xDJnymv43XZovptt4AGKWZZI6zjk0',
    appId: '1:723344246922:ios:d14372179a438a72540573',
    messagingSenderId: '723344246922',
    projectId: 'roommate-c6d62',
    storageBucket: 'roommate-c6d62.firebasestorage.app',
    iosBundleId: 'com.example.gp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALC3xDJnymv43XZovptt4AGKWZZI6zjk0',
    appId: '1:723344246922:ios:d14372179a438a72540573',
    messagingSenderId: '723344246922',
    projectId: 'roommate-c6d62',
    storageBucket: 'roommate-c6d62.firebasestorage.app',
    iosBundleId: 'com.example.gp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg-oKE9BplgVT90lAp1aslt3VZPAoUfxw',
    appId: '1:723344246922:web:3c4aa86d52527cf4540573',
    messagingSenderId: '723344246922',
    projectId: 'roommate-c6d62',
    authDomain: 'roommate-c6d62.firebaseapp.com',
    storageBucket: 'roommate-c6d62.firebasestorage.app',
    measurementId: 'G-Q9B0Z5FC7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJCpVeqyP6Z5SZhWTnnDIYHCHTihaKne4',
    appId: '1:723344246922:android:6dc908c1c68fdbb6540573',
    messagingSenderId: '723344246922',
    projectId: 'roommate-c6d62',
    storageBucket: 'roommate-c6d62.firebasestorage.app',
  );

}